version: "3.8"

services:
  docker:
    image: registry:2.8.2
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./var/docker:/var/lib/registry
      - ./etc/docker:/etc/docker/registry

  zot:
    # image: ghcr.io/project-zot/zot-linux-arm64:v2.0.0-rc6
    image: ghcr.io/sagikazarmark/zot:auth-fix
    ports:
      - 127.0.0.1:5001:5001
    volumes:
      - ./var/zot:/tmp/zot
      - ./etc/zot:/etc/zot
